---
- name: Setup a simple python app
  #connection: local
  gather_facts: false
  hosts: ansible-host
  tasks:
  ## Simple ansible test
  - name: Write something
    debug: msg="Hi"
  ## Installing MySQL server and client.
  - name: Install MySQL server
    apt:
      name: mysql-server
      state: present
    become: true
  - name: Install MySQL Client
    apt:
      name: mysql-client-core-5.7
      state: present
    become: true
  - name: Running MySQL server in instance
    systemd:
      state: started #1. Change to stopped and see what happens
      name: mysql
    become: true #2. Remove this line and check what happens
  ## Command to test: sudo systemctl status mysql
  ## Inserting test data
  - name: Get updated files from git repository
    git:
      repo: "https://{{ githubusername | urlencode }}:{{ githubpassword | urlencode }}@github.com/rajalakshmi-v15/ansible-hands-on.git"
      dest: "/tmp/coderepo"
 
  - name: Inserting test data
    shell:
      cmd: mysql mysql < init_db.sql
    become: true
    args:
      chdir: /tmp/coderepo
  - name: Installing pip
    apt:
      name: python3-pip
      state: present
    become: true

  - name: Install flask python package
    pip:
      name: flask
    become: true
  - name: Install flask-mysql python package
    pip:
      name: flask-mysql
    become: true
 # Go into /tmp/coderepo of host machine and execute FLASK_APP=app.py flask run --host=0.0.0.0
